// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using OKRs.Data;
using System;

namespace OKRs.Migrations
{
    [DbContext(typeof(ObjectivesDbContext))]
    [Migration("20240820084800_AddCompletionRateToKeyResult")]
    partial class AddCompletionRateToKeyResult
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OKRs.Models.KeyResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("CompletionRate")
                        .HasColumnType("decimal(3,2)");

                    b.Property<DateTime>("Created");

                    b.Property<string>("Description");

                    b.Property<DateTime>("LastUpdated");

                    b.Property<Guid?>("ObjectiveId");

                    b.HasKey("Id");

                    b.HasIndex("ObjectiveId");

                    b.ToTable("KeyResults");
                });

            modelBuilder.Entity("OKRs.Models.Objective", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("LastUpdated");

                    b.Property<string>("Title");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.ToTable("Objectives");
                });

            modelBuilder.Entity("OKRs.Models.KeyResult", b =>
                {
                    b.HasOne("OKRs.Models.Objective")
                        .WithMany("KeyResults")
                        .HasForeignKey("ObjectiveId");
                });
#pragma warning restore 612, 618
        }
    }
}